<a href="https://colab.research.google.com/github/TH-Bow/audibleBook_Revenue/blob/main/audibleBook_Revenue.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Collection with Python Library Pandas

##Import Library pandas

In [ ]:
import pandas as pd

##Download .csv files to colab


 [audible_data.csv](https://github.com/TH-Bow/audibleBook_Revenue/blob/main/audible_data.csv) AND [audible_transaction.csv](https://www.dropbox.com/scl/fi/f2fqb04ca9amhfwmwjsjt/audible_transaction.csv.zip?rlkey=0z0exq3ho5qy3nytddh6t1et4&dl=0)

In [ ]:
#read file "audible_data"
audible_data = pd.read_csv("/content/audible_data.csv")
audible_transaction = pd.read_csv("/content/audible_transaction.csv")

##Set Column `Book_ID` to be the index

In [ ]:
audible_data = audible_data.set_index("Book_ID")

##Delete column Unnamed

In [ ]:
audible_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2269 entries, 1 to 2269
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            2269 non-null   int64
 1   Book Title            2269 non-null   object
 2   Book Subtitle         1471 non-null   object
 3   Book Author           2269 non-null   object
 4   Book Narrator         2211 non-null   object
 5   Audio Runtime         2269 non-null   object
 6   Audiobook_Type        2206 non-null   object
 7   Categories            2152 non-null   object
 8   Rating                2033 non-null   object
 9   Total No. of Ratings  1975 non-null   float64
 10  Price                 2269 non-null   object
dtypes: float64(1), int64(1), object(9)
memory usage: 212.7+ KB

In [ ]:
audible_data = audible_data.drop("Unnamed: 0", axis=1)

#Transaction Dataframe

##Join table: audible_transaction & audible_data

Use column `Book_ID` to merge transaction dataframe and audible dataframe to see the book's price of each transaction

In [ ]:
transaction = audible_transaction.merge(
    audible_data, how="left", left_on="book_id", right_on="Book_ID"
    )

In [ ]:
transaction = transaction.drop("Unnamed: 0", axis=1)

In [ ]:
transaction[:3]

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,NaN,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,$35.00
1,2021-05-01 00:00:03,561b26c1,829,United States of America,The 5 Love Languages of Children,The Secret to Loving Children Effectively,Gary Chapman,Chris Fabry,5 hrs and 48 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,2441.0,$19.59
2,2021-05-01 00:00:04,81f149e5,1391,Japan,The Guardians,A Novel,John Grisham,Michael Beck,11 hrs and 50 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,26781.0,$31.50

#Conversion Rate Dataframe

##Get data from REST API

URL : [Currency conversion API](https://r2de2-workshop-vmftiryt6q-ts.a.run.app/usd_thb_conversion_rate)

In [ ]:
import requests
url = "https://r2de2-workshop-vmftiryt6q-ts.a.run.app/usd_thb_conversion_rate"
r = requests.get(url)
result_conversion_rate = r.json()

In [ ]:
result_conversion_rate

{'conversion_rate': {'2021-08-12': 33.084,
  '2021-08-11': 33.145,
  '2021-08-10': 33.46,
  '2021-08-09': 33.464,
  '2021-08-08': 33.395,
  '2021-08-07': 33.422,
  '2021-08-06': 33.45,
  '2021-08-05': 33.263,
  '2021-08-04': 33.137,
  '2021-08-03': 33.022,
  '2021-08-02': 32.957,
  '2021-08-01': 32.895,
  '2021-07-31': 32.887,
  '2021-07-30': 32.887,
  '2021-07-29': 32.87,
  '2021-07-28': 32.82,
  '2021-07-27': 32.937,
  '2021-07-26': 32.929,
  '2021-07-25': 32.94,
  '2021-07-24': 32.963,
  '2021-07-23': 32.928,
  '2021-07-22': 32.887,
  '2021-07-21': 32.857,
  '2021-07-20': 32.829,
  '2021-07-19': 32.854,
  '2021-07-18': 32.807,
  '2021-07-17': 32.795,
  '2021-07-16': 32.783,
  '2021-07-15': 32.686,
  '2021-07-14': 32.605,
  '2021-07-13': 32.654,
  '2021-07-12': 32.664,
  '2021-07-11': 32.506,
  '2021-07-10': 32.482,
  '2021-07-09': 32.512,
  '2021-07-08': 32.534,
  '2021-07-07': 32.334,
  '2021-07-06': 32.271,
  '2021-07-05': 32.112,
  '2021-07-04': 32.136,
  '2021-07-03': 32.125,
  '2021-07-02': 32.126,
  '2021-07-01': 32.073,
  '2021-06-30': 32.029,
  '2021-06-29': 32.108,
  '2021-06-28': 31.918,
  '2021-06-27': 31.785,
  '2021-06-26': 31.816,
  '2021-06-25': 31.816,
  '2021-06-24': 31.898,
  '2021-06-23': 31.825,
  '2021-06-22': 31.681,
  '2021-06-21': 31.617,
  '2021-06-20': 31.461,
  '2021-06-19': 31.437,
  '2021-06-18': 31.439,
  '2021-06-17': 31.422,
  '2021-06-16': 31.297,
  '2021-06-15': 31.162,
  '2021-06-14': 31.117,
  '2021-06-13': 31.077,
  '2021-06-12': 31.074,
  '2021-06-11': 31.092,
  '2021-06-10': 31.14,
  '2021-06-09': 31.167,
  '2021-06-08': 31.202,
  '2021-06-07': 31.176,
  '2021-06-06': 31.133,
  '2021-06-05': 31.125,
  '2021-06-04': 31.125,
  '2021-06-03': 31.209,
  '2021-06-02': 31.108,
  '2021-06-01': 31.169,
  '2021-05-31': 31.193,
  '2021-05-30': 31.238,
  '2021-05-29': 31.252,
  '2021-05-28': 31.257,
  '2021-05-27': 31.297,
  '2021-05-26': 31.281,
  '2021-05-25': 31.328,
  '2021-05-24': 31.323,
  '2021-05-23': 31.37,
  '2021-05-22': 31.361,
  '2021-05-21': 31.361,
  '2021-05-20': 31.378,
  '2021-05-19': 31.413,
  '2021-05-18': 31.42,
  '2021-05-17': 31.492,
  '2021-05-16': 31.365,
  '2021-05-15': 31.33,
  '2021-05-14': 31.33,
  '2021-05-13': 31.344,
  '2021-05-12': 31.304,
  '2021-05-11': 31.158,
  '2021-05-10': 31.107,
  '2021-05-09': 31.033,
  '2021-05-08': 31.042,
  '2021-05-07': 31.042,
  '2021-05-06': 31.226,
  '2021-05-05': 31.13,
  '2021-05-04': 31.188,
  '2021-05-03': 31.132,
  '2021-05-02': 31.122,
  '2021-05-01': 31.14,
  '2021-04-30': 31.139,
  '2021-04-29': 31.197,
  '2021-04-28': 31.344,
  '2021-04-27': 31.355,
  '2021-04-26': 31.427,
  '2021-04-25': 31.421,
  '2021-04-24': 31.411,
  '2021-04-23': 31.412,
  '2021-04-22': 31.378,
  '2021-04-21': 31.3,
  '2021-04-20': 31.281,
  '2021-04-19': 31.203,
  '2021-04-18': 31.226,
  '2021-04-17': 31.204,
  '2021-04-16': 31.203,
  '2021-04-15': 31.165,
  '2021-04-14': 31.329,
  '2021-04-13': 31.496,
  '2021-04-12': 31.482,
  '2021-04-11': 31.462,
  '2021-04-10': 31.454,
  '2021-04-09': 31.451,
  '2021-04-08': 31.433,
  '2021-04-07': 31.387,
  '2021-04-06': 31.288,
  '2021-04-05': 31.342,
  '2021-04-04': 31.244,
  '2021-04-03': 31.256,
  '2021-04-02': 31.29,
  '2021-04-01': 31.194}}

The data type of the conversion rate API is dictionay.

it should to be converted to Dataframe before joining to `transaction dataframe`

In [ ]:
print(type(result_conversion_rate))
assert isinstance(result_conversion_rate, dict)

##Convert to Pandas Dataframe

In [ ]:
conversion_rate = pd.DataFrame(result_conversion_rate)
conversion_rate

            conversion_rate
2021-04-01           31.194
2021-04-02           31.290
2021-04-03           31.256
2021-04-04           31.244
2021-04-05           31.342
...                     ...
2021-08-08           33.395
2021-08-09           33.464
2021-08-10           33.460
2021-08-11           33.145
2021-08-12           33.084

[134 rows x 1 columns]

##Rename index column to `Date` column

In [ ]:
conversion_rate = conversion_rate.reset_index().rename(columns={"index": "Date"})
conversion_rate

           Date  conversion_rate
0    2021-04-01           31.194
1    2021-04-02           31.290
2    2021-04-03           31.256
3    2021-04-04           31.244
4    2021-04-05           31.342
..          ...              ...
129  2021-08-08           33.395
130  2021-08-09           33.464
131  2021-08-10           33.460
132  2021-08-11           33.145
133  2021-08-12           33.084

[134 rows x 2 columns]

In [ ]:
conversion_rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             134 non-null    object
 1   conversion_rate  134 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

##convert `Date` Column to datetime

In [ ]:
conversion_rate['Date'] = pd.to_datetime(conversion_rate['Date']).dt.date

#Output Dataframe

##Join table: transaction & conversion_rate


first of all copy the `timestamp` column to the `date` column then convert to datetime.

In [ ]:
transaction['date'] = transaction['timestamp']
transaction[:3]

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price,date
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,NaN,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,$35.00,2021-05-01 00:00:01
1,2021-05-01 00:00:03,561b26c1,829,United States of America,The 5 Love Languages of Children,The Secret to Loving Children Effectively,Gary Chapman,Chris Fabry,5 hrs and 48 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,2441.0,$19.59,2021-05-01 00:00:03
2,2021-05-01 00:00:04,81f149e5,1391,Japan,The Guardians,A Novel,John Grisham,Michael Beck,11 hrs and 50 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,26781.0,$31.50,2021-05-01 00:00:04

In [ ]:
transaction['date'] = pd.to_datetime(transaction['date']).dt.date

Use column `Date` to merge transaction dataframe and conversion rate dataframe

In [ ]:
final_df = transaction.merge(conversion_rate, how="left", left_on="date", right_on="Date")
final_df.head()

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price,date,Date,conversion_rate
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,NaN,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,$35.00,2021-05-01,2021-05-01,31.14
1,2021-05-01 00:00:03,561b26c1,829,United States of America,The 5 Love Languages of Children,The Secret to Loving Children Effectively,Gary Chapman,Chris Fabry,5 hrs and 48 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,2441.0,$19.59,2021-05-01,2021-05-01,31.14
2,2021-05-01 00:00:04,81f149e5,1391,Japan,The Guardians,A Novel,John Grisham,Michael Beck,11 hrs and 50 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,26781.0,$31.50,2021-05-01,2021-05-01,31.14
3,2021-05-01 00:00:07,4f218413,1586,Taiwan,How to Be a 3% Man,NaN,Corey Wayne,Corey Wayne,7 hrs and 33 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,11459.0,$19.95,2021-05-01,2021-05-01,31.14
4,2021-05-01 00:00:18,a4066781,300,United States of America,Napoleon Hill's Outwitting the Devil,The Secret to Freedom and Success,Napoleon Hill,Dan John Miller,5 hrs and 51 mins,Unabridged Audiobook,Business & Careers,4.8,9305.0,$17.49,2021-05-01,2021-05-01,31.14

##Delete dollar sign ($)

The data type of the `Price` column is string. ($20.52) delete dollar sign every single row then converted the price column type to float.

In [ ]:
final_df["Price"] = final_df.apply(lambda x: x["Price"].replace("$",""), axis=1)
final_df.head()

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price,date,Date,conversion_rate
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,NaN,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,35.00,2021-05-01,2021-05-01,31.14
1,2021-05-01 00:00:03,561b26c1,829,United States of America,The 5 Love Languages of Children,The Secret to Loving Children Effectively,Gary Chapman,Chris Fabry,5 hrs and 48 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,2441.0,19.59,2021-05-01,2021-05-01,31.14
2,2021-05-01 00:00:04,81f149e5,1391,Japan,The Guardians,A Novel,John Grisham,Michael Beck,11 hrs and 50 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,26781.0,31.50,2021-05-01,2021-05-01,31.14
3,2021-05-01 00:00:07,4f218413,1586,Taiwan,How to Be a 3% Man,NaN,Corey Wayne,Corey Wayne,7 hrs and 33 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,11459.0,19.95,2021-05-01,2021-05-01,31.14
4,2021-05-01 00:00:18,a4066781,300,United States of America,Napoleon Hill's Outwitting the Devil,The Secret to Freedom and Success,Napoleon Hill,Dan John Miller,5 hrs and 51 mins,Unabridged Audiobook,Business & Careers,4.8,9305.0,17.49,2021-05-01,2021-05-01,31.14

##Coverted to float

converted the `Price` column to float data type

In [ ]:
final_df["Price"] = final_df["Price"].astype(float)
final_df.dtypes

timestamp                object
user_id                  object
book_id                   int64
country                  object
Book Title               object
Book Subtitle            object
Book Author              object
Book Narrator            object
Audio Runtime            object
Audiobook_Type           object
Categories               object
Rating                   object
Total No. of Ratings    float64
Price                   float64
date                     object
Date                     object
conversion_rate         float64
dtype: object

##Book's price in Thai Baht

Added the `THBPrice` column to the final_df dataframe

In [ ]:
final_df["THBprice"] = final_df["Price"] * final_df["conversion_rate"]
final_df.head()

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price,date,Date,conversion_rate,THBprice
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,NaN,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,35.00,2021-05-01,2021-05-01,31.14,1089.9000
1,2021-05-01 00:00:03,561b26c1,829,United States of America,The 5 Love Languages of Children,The Secret to Loving Children Effectively,Gary Chapman,Chris Fabry,5 hrs and 48 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,2441.0,19.59,2021-05-01,2021-05-01,31.14,610.0326
2,2021-05-01 00:00:04,81f149e5,1391,Japan,The Guardians,A Novel,John Grisham,Michael Beck,11 hrs and 50 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,26781.0,31.50,2021-05-01,2021-05-01,31.14,980.9100
3,2021-05-01 00:00:07,4f218413,1586,Taiwan,How to Be a 3% Man,NaN,Corey Wayne,Corey Wayne,7 hrs and 33 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,11459.0,19.95,2021-05-01,2021-05-01,31.14,621.2430
4,2021-05-01 00:00:18,a4066781,300,United States of America,Napoleon Hill's Outwitting the Devil,The Secret to Freedom and Success,Napoleon Hill,Dan John Miller,5 hrs and 51 mins,Unabridged Audiobook,Business & Careers,4.8,9305.0,17.49,2021-05-01,2021-05-01,31.14,544.6386

delete the `date` column.

In [ ]:
final_df = final_df.drop("date", axis=1)

SAVE file to CSV